### ISSUE TITLE
Last frame is no work in timeline

### ISSUE THREAD

**Issue by Bald-Rabbit** [Haruma-K/UnityUIPlayables#6]
Last frame and second last frame is same value In play.  So I gress last frame is Last frame is no work.

**Comment by Haruma-K** [comment]
Please write down the steps to reproduce the issue.

**Comment by Bald-Rabbit** [comment]
Just open one timeline，and set to last frame. For example, Canvas Group Aniamtion Clip the star value 0 and end value 1, end of animation, the vaue will be 0.99, it not 1. In PlayableBehaviour, the clip last frame intputWeight is 0, maybe it the reason i think.

**Comment by Langdex** [comment]
Because in the function **AnimationBehavior.EvaluateCurve()**, the range of return values for **Mathf.Repeat(progress, 1.0f)** is [0,1) and will never be equal to 1.

**Comment by Haruma-K** [comment]
I apologize for the late response. Regarding the issue where the last frame of the Timeline clip is not evaluated, this is due to the specifications of Unity.

https://forum.unity.com/threads/animation-events-on-last-frame-arent-fired-in-timeline-when-its-the-last-frame-of-the-timeline.791258/

 The EvaluateCurve issue pointed out by @Langdex  is a separate bug and I will fix it.

**Comment by Haruma-K** [comment]
> Regarding the issue where the last frame of the Timeline clip is not evaluated, this is due to the specifications of Unity.

This can also be reproduced with the Unity official asset "Default Playables."

![image](https://github.com/user-attachments/assets/67f23e21-a6bc-4823-877e-4e382b104884)

**Comment by Haruma-K** [comment]
> Because in the function AnimationBehavior.EvaluateCurve(), the range of return values for Mathf.Repeat(progress, 1.0f) is [0,1) and will never be equal to 1.

fixed: https://github.com/Haruma-K/UnityUIPlayables/releases/tag/0.1.3
